### ISSUE TITLE
How to get pkp_hash？

### ISSUE THREAD

**Issue by jeffy7** [approov/react-native-cert-pinner#14]
by Report URI at https://report-uri.com/home/pkp_hash.  not find

so  how to get pkp_hash？

**Comment by RobinTack** [comment]
You can use this website instead: https://www.ssllabs.com/ssltest/analyze.html?d=demo%2dserver.approovr.io&latest

**Comment by jeffy7** [comment]
hello ,I got Pin SHA256 through the above website.
And then I set it up like this.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/5660983/66735881-326eb080-ee9a-11e9-9222-8c62d194dab3.png">

But the result is incorrect. I can access our servers normally in Debug mode. Once I close Debug, I can't access our servers. Is there something wrong with my setup or what?

**Comment by ahmetozalp** [comment]
problem fix?

**Comment by jeffy7** [comment]
> problem fix?

yeah.
