### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by CoenWarmer** [approov/react-native-cert-pinner#19]
In the `README.md` there is noted that this repo will be upgraded to Approov version 2 'soon'. That was since posted in August 2019. Are there still plans to do that, or more to the point, is this project still being maintained? @skiph @Exadra37 @sfstpala @ma-pe

**Comment by Exadra37** [comment]
Yes we are working on it.

Meanwhile you can see this [quick start](https://github.com/approov/quickstart-react-native) for React Native with Approov 2.

**Comment by CoenWarmer** [comment]
Thanks @Exadra37!
