### ISSUE TITLE
Timeline: iOS Support

### ISSUE THREAD

**Issue by ma-pe** [approov/react-native-cert-pinner#2]
Hey there,

thank you very much for releasing this library. This is really massive for me, because you can use the react-native fetch library which supports blobs.

Do you have any timeline for the iOS support in mind. We are looking forward to release our app for android and ios soon and I'd be more than happy to help by any means.

Greetings
Malte

**Comment by skiph** [comment]
With version 0.4, I have added initial support for iOS. Give it a try.
