### ISSUE TITLE
Always getting accept when fetch data

### ISSUE THREAD

**Issue by barak109** [approov/react-native-cert-pinner#22]
Thank you about the package!, I'm trying to fetch data with some different pins and all the time i get the data even when the pins is incorrect, i did all the process that mention in the Getting started and the usage (exactly the same).
I tried your example project and it doesn't work too(some time goes to catch and some times not...).
any advise or maybe there is a problem in the last update of the package..?

I use react native 59.8

Edit-
It's so weird i tried to run the example folder with some pins randomly and there some pins that return "hello world" and some Error..

**Comment by annkiitagrawaal-gep** [comment]
hi @barak109 What was the issue and how did you fix it?
