### ISSUE TITLE
report-uri.com/home/pkp_hash is 404

### ISSUE THREAD

**Issue by pke** [approov/react-native-cert-pinner#28]
Is there an alternative?

**Comment by sulfanoaf** [comment]
try this https://www.ssllabs.com/ssltest/analyze.html

**Comment by pke** [comment]
Too slow, and does too much that I don't need.
I wrote my own:

https://pinni.vercel.app/api/pin/google.com,google.co.uk
https://pinni.vercel.app/api/pin/google.com,google.co.uk?format=application/json
https://pinni.vercel.app/api/pin/google.com,google.co.uk?format=text/plain

**Comment by murat-mehmet** [comment]
hey, any update on this?
