### ISSUE TITLE
How to check, is ssl pinning works?

### ISSUE THREAD

**Issue by SergeyKatugin** [approov/react-native-cert-pinner#34]
I added this package, implement all settings. Api request works fine.

But i not sure, is ssl pinning working or not.

How can i check it?

**Comment by ssuchanowski** [comment]
Use Charles on you phone or proxyman (mac). If you perform man in the middle using sniffing tool I won't return any content for the SSL Pinned domains

**Comment by suusofttruongnv** [comment]
> I added this package, implement all settings. Api request works fine.
> 
> But i not sure, is ssl pinning working or not.
> 
> How can i check it?

Hi Bro, are you using it with axios ?

**Comment by SergeyKatugin** [comment]
> > I added this package, implement all settings. Api request works fine.
> > But i not sure, is ssl pinning working or not.
> > How can i check it?
> 
> Hi Bro, are you using it with axios ?

I fixed it. I checked via logs in Xcode.
Axios doesn’t works, I used api which recommended in documentation.
Works correctly.
But i forgot change cert and it broke my app. Be careful)
