### ISSUE TITLE
Erro to execute npx pinset get  - in generated 'GeneratedCertificatePinner.java'

### ISSUE THREAD

**Issue by maxocg** [approov/react-native-cert-pinner#4]
Hello, I am trying to run the 'gen' command but this error is occurring, what can it be? Have you seen anything like that?

"react": "16.5.0",
"react-native": "0.57.0"
"react-native-cert-pinner": "^0.4.1"

`Updating java file './android/app/src/main/java/com/criticalblue/reactnative/GeneratedCertificatePinner.java'.
Java file './android/app/src/main/java/com/criticalblue/reactnative/GeneratedCertificatePinner.java' error: Error: ENOENT: no such file or directory, open './android/app/src/main/java/com/criticalblue/reactnative/GeneratedCertificatePinner.java'`

**Comment by maxocg** [comment]
I created the .Java file manually and it worked.
Thank you!

**Comment by skiph** [comment]
I suspect the directory path did not exist, and it is something I missed in my testing. Until corrected, manually creating the <android-project>/app/src/main/java/com/criticalblue/reactnative/ path one time should workaround it.

**Comment by maxocg** [comment]
I created the directory path manually and it worked.
Thanks.
